### ISSUE TITLE
request timed out when downloading less than 10 images

### ISSUE THREAD

**Issue by garfieldlover7271978** [dxrcy/everygarf#2]
works fine when using --no-proxy

**Comment by dxrcy** [comment]
Hello :)

Please provide more information about the problem, as I am unable to reproduce this.

1. Are you using the default `--timeout` and `--initial-timeout` arguments? And does the problem still occur when changing these values?
2. Can you tell me what the full error message is; Especially the part in bold red.

Thank you for opening the first issue on this project!

**Comment by garfieldlover7271978** [comment]
[warning] [Attempt 4] 2024-06-05 #1 Failed: Fetching image url - Request timed out. If this happens often, check your connection, or change the `--timeout` argument.
    2024-06-05  #01   0%  [1••]
[warning] [Attempt 5] 2024-06-04 #0 Failed: Fetching image url - Request timed out. If this happens often, check your connection, or change the `--timeout` argument.
    2024-06-04  #00   0%  [1••]
[warning] [Attempt 5] 2024-06-05 #1 Failed: Fetching image url - Request timed out. If this happens often, check your connection, or change the `--timeout` argument.

**Comment by dxrcy** [comment]
It looks like the command output was cut off before the error message...

> The default proxy is blocked by my ISP

1. Are you able to try with a VPN connection?

2. Does it work to add the option `--source fandom`?

**Comment by garfieldlover7271978** [comment]
The error message was something like "10 attempts reached. exiting".
1. Yes, it works
2. No

**Comment by dxrcy** [comment]
Are you able to setup a custom proxy service following https://github.com/dxrcy/everygarf?tab=readme-ov-file#setup-a-custom-proxy-service-with-cloudflare-worker

This might be your best bet, as I can't seem to reproduce your issue.

**Comment by garfieldlover7271978** [comment]
I think that the problem might be that without using `--no-proxy`, it still uses the proxy when downloading less than 10 images, and skips the proxy ping.

**Comment by dxrcy** [comment]
Oh...I see what you mean now!

This  is intented behaviour.

The proxy is always enabled, unless `--no-proxy` is given. The proxy ping is only disabled when few images are being downloaded, to avoid unnecessary pinging for scheduled downloads.

Although, the proxy should only be used when image urls are not cached (or downloaded from the remote cache), as the image url fetching is the more unreliable and more often rate-limited component. This can be forced with `--no-cache`.

This is most likely why it stopped working for you when downloading comics from 2024; I have not updated the remote cache file for a little while.
If you try it now it should work, as I have just pushed a change.

**Comment by garfieldlover7271978** [comment]
Oh! thanks for clarifying
