### ISSUE TITLE
'Fandom' source option just downloads the wiki's favicon

### ISSUE THREAD

**Issue by garfieldlover7271978** [dxrcy/everygarf#3]
This is the command line:
everygarf gocomics -f png --source fandom --no-cache --no-proxy

**Comment by dxrcy** [comment]
Thanks for noticing this!
The fandom website must have changed how the webpage loads, so the code can't find the correct image.
It looks like I am able to send a JSON request instead.

**Comment by dxrcy** [comment]
Hm. The request urls which the fandom website uses are *very* inconsistent.
I don't think there is a good way to fetch the image urls, without mapping each date to a request url (which defeats the point).

It looks like I will have to drop support for `--source fandom`, at least for now.
